---

- name: "Remove {{ goss_test_directory }}"
  ansible.builtin.file:
    path: "{{ goss_test_directory }}"
    state: absent

- name: Remove goss
  ansible.builtin.file:
    path: "{{ goss_path }}/goss"
    state: absent

- name: Remove dgoss
  ansible.builtin.file:
    path: "{{ goss_path }}/dgoss"
    state: absent
