---

- name: Install ca-certificates
  ansible.builtin.apt:
    name: ca-certificates
  register: network_access
  until: network_access is success
  retries: 10
  delay: 2
  when: ansible_os_family == 'Debian'
  tags:
    - base_goss

- name: Install EPEL
  when: ansible_os_family == 'RedHat'
  ansible.builtin.yum:
    name: epel-release
    state: present
  register: epel_install
  until: epel_install is success
  retries: 3
  delay: 3

- name: Install jmespath
  # when: ansible_os_family == 'RedHat'
  ansible.builtin.package:
    name: python3-jmespath
    state: present
    update_cache: true
  register: network_access
  until: network_access is success
  retries: 3
  delay: 10
  tags:
    - base_goss
