---
# tasks for base_goss
# Standards: 0.2
# yamllint disable rule:line-length

- name: Local download
  when: goss_download == 'localhost'
  block:
    - name: Get goss binary
      become: false
      delegate_to: localhost
      ansible.builtin.get_url:
        url: "{{ goss_url }}"
        checksum: "sha256:{{ goss[goss_version].sha256sum }}"
        validate_certs: false
        dest: "/tmp/goss"
        mode: 0755
      register: network_access
      until: network_access is success
      retries: 10
      delay: 2
      tags:
        - base_goss

    - name: Ensure we have local copy of goss
      become: false
      delegate_to: localhost
      ansible.builtin.stat:
        path: /tmp/goss
      register: goss_bin
      tags:
        - base_goss

    - name: Copy goss to remote
      ansible.builtin.copy:
        src: "/tmp/goss"
        dest: "{{ goss_path }}/goss"
        owner: "{{ goss_user }}"
        group: "{{ goss_user }}"
        mode: 0755
      when: goss_bin.stat.exists
      tags:
        - base_goss


- name: Get goss binary directly
  ansible.builtin.get_url:
    url: "{{ goss_url }}"
    checksum: "sha256:{{ goss[goss_version].sha256sum }}"
    validate_certs: false
    dest: "{{ goss_path }}/goss"
    owner: "{{ goss_user }}"
    group: "{{ goss_user }}"
    mode: 0755
  register: network_access
  until: network_access is success
  retries: 10
  delay: 2
  when: goss_download == 'direct'
  tags:
    - base_goss

- name: Copy dgoss to remote
  ansible.builtin.copy:
    src: "dgoss"
    dest: "{{ goss_path }}/dgoss"
    mode: 0755
  no_log: true
  when: goss_install_dgoss|bool
  tags:
    - base_goss

- name: "Ensure presence of directory {{ goss_test_directory }}"
  ansible.builtin.file:
    path: "{{ goss_test_directory }}"
    state: directory
    owner: "{{ goss_user }}"
    group: "{{ goss_user }}"
    mode: "{{ goss_test_directory_mode }}"
  tags:
    - base_goss

- name: Copy test_goss.yaml to remote
  ansible.builtin.template:
    src: test_goss.yaml.j2
    dest: "{{ goss_test_directory }}/test_goss.yaml"
    mode: 0644
  tags:
    - base_goss

- name: Copy goss.yaml to remote
  ansible.builtin.template:
    src: goss.yaml.j2
    dest: "{{ goss_test_directory }}/goss.yaml"
    mode: 0644
  tags:
    - base_goss
    - validate


...
