---
#
- name: Cleanup
  hosts: all
  gather_facts: true
  become: true
  vars:
    this_role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
    desired_state: absent

  tasks:
    - name: Removing things created by role
      ansible.builtin.include_role:
        name: "{{ this_role }}"
