---
#
- name: Converge
  hosts: all
  gather_facts: true
  become: true
  vars:
    this_role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"

  tasks:
    - name: Play the role
      ansible.builtin.include_role:
        name: "{{ this_role }}"
...
