
resources:
  - repo: self
steps:
- task: PackerTool@0
  inputs:
    version: '1.8.4'
- task: Packer@1
  inputs:
    connectedServiceType: 'azure'
    azureSubscription: 'AzureDevOps'
    templatePath: 'alma8.pkr.hcl'
    command: 'init'
- task: Packer@1
  inputs:
    connectedServiceType: 'azure'
    azureSubscription: 'AzureDevOps'
    templatePath: 'alma8.pkr.hcl'
    command: 'validate'
