# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  - repo: self
steps:
- task: riezebosch.Packer.PackerTool.PackerTool@0
  displayName: 'Use Packer 1.8.4'
  inputs:
    version: 1.8.4
- task: Packer@1
  displayName: 'Packer build'
 
  inputs:
    connectedServiceType: azure
    templatePath: alma8.pkr.hcl
    force: true
    options: --only azure-arm.alma8
