#!/usr/bin/env ansible-playbook
---

- name: Provision image
  hosts: all:!localhost
  become: true
  gather_facts: true

  tasks:
    - name: Hello ansible
      ansible.builtin.debug:
        msg: "Hello ansible"

...
