---
#
# Tasks
#
- name: Install the tftp and tftp-server packages via yum
  ansible.builtin.package:
    name:
      - tftp
      - tftp-server
    state: present
  become: true

- name: Make sure group {{ TFTP_user }} exists
  ansible.builtin.group:
    name: "{{ TFTP_user }}"
    system: true
    local: true
    state: present
  become: true

- name: Make sure user {{ TFTP_user }} exists
  ansible.builtin.user:
    name: "{{ TFTP_user }}"
    group: "{{ TFTP_user }}"
    home: "{{ tftpboot_folder }}"
    comment: TFTP service account
    create_home: false
    password: "!"
    password_lock: true
    shell: /sbin/nologin
    system: true
    local: true
    state: present
  become: true

- name: Add specified users to group {{ TFTP_user }}
  ansible.builtin.user:
    name: "{{ item }}"
    # note that append and groups are mutually exclusive with local: true
    append: true
    groups: "{{ [ TFTP_user ] }}"
  become: true
  loop: "{{ TFTP_group_members }}"

# Note that we don't need to remove the {{ TFTP_user }} group from
# {{ TFTP_group_members }} because when the group is removed members loose
# their membership automatically.
- name: Create tftpboot home
  ansible.builtin.file:
    path: "{{ tftpboot_folder }}"
    state: directory
    # Note the sticky group bit
    mode: '02775'
    owner: "{{ TFTP_user }}"
    group: "{{ TFTP_user }}"
  become: true

- name: Make sure {{ config_destination }} exists
  ansible.builtin.file:
    name: "{{ config_destination }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: true

- name: Override default TFTP server options
  ansible.builtin.template:
    src: override.j2
    dest: "{{ config_destination }}/override.conf"
    mode: '0644'
  become: true

- name: Enable TFTP activation socket
  ansible.builtin.systemd:
    name: tftp.socket
    enabled: true
    state: started
  become: true

- name: Allow TFTP server to read its home directory
  when: ansible_facts.selinux.status in ['enforcing', 'permissive']
  seboolean:
    name: tftp_home_dir
    state: true
    persistent: true
  become: true

- name: Enable firewall for TFTP
  ansible.posix.firewalld:
    zone: internal
    service: tftp
    permanent: true
    immediate: true
    state: enabled
  become: true

- name: Find files and subdirectories under {{ tftpboot_folder }}
  ansible.builtin.find:
    paths: "{{ [ tftpboot_folder ] }}"
    recurse: true
    file_type: any
  register: found
  become: true

- name: "Fix permission and group membership of files and subdirectories \
  of {{ tftpboot_folder }}"
  ansible.builtin.file:
    path: "{{ item.path }}"
    group: "{{ TFTP_user }}"
    # See chmod(1) for an explanation of X
    mode: "{{ 'u=rwx,g=rwxs,o=rx' if item.isdir else 'u=rwX,g=rwX,o=rX' }}"
    modification_time: preserve
    access_time: preserve
    # attributes, se{user,role,type,level}?
  loop: "{{ found.files }}"
  when: not ( item.islnk or ( item.nlink > 1 and not item.isdir ) )
  loop_control:
    label: "{{ item.path }}"
  become: true
...
