---
# defaults file for install_goss
# Standards: 0.2
desired_state: present
verify_state: false
goss_report: false
goss_version: "v0.3.20"
goss_path: "/usr/bin"
goss_arch: amd64
goss_dst: /usr/bin/goss
# yamllint disable-line rule:line-length
goss_url: "https://github.com/goss-org/goss/releases/download/{{ goss_version }}/goss-linux-{{ goss_arch }}"
goss_test_directory: /etc/goss.d
goss_test_directory_mode: 0700
goss_format: tap
goss_user: root
goss_install_dgoss: true
goss_download: localhost
...
