---
# This playbook executes the tasks from the role
- name: Converge
  hosts: all
  gather_facts: false
  become: true
  vars:
    role_name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"

  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:

    - name: Include role
      ansible.builtin.include_role:
        name: "{{ role_name }}"
