---
- name: Include OS-specific variables.
  # yamllint disable-line rule:line-length
  ansible.builtin.include_vars: "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"
  tags:
    - goss

- name: Update repositories cache
  when: ansible_os_family == 'Debian'
  ansible.builtin.apt:
    update_cache: true

- name: Ensure packages are installed
  ansible.builtin.package:
    name: "{{ nettime_packages }}"
    state: present
  register: nettime_package
  ignore_errors: true

- name: Manage firewall
  when: manage_firewall
  ansible.builtin.include_tasks: firewall.yml

- name: Enable systemd-timedated
  when: nettime_package.failed
  ansible.builtin.systemd:
    name: systemd-timedated
    enabled: true
  notify: "Restart timedated"

- name: Disable conflicting services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  register: service_result
  failed_when:
    - service_result is failed
    - ('Could not find' not in service_result.msg)
  loop:
    - systemd-timesyncd
    - ntpd

- name: Configure chrony key
  when:
    - net_allow is defined
    - net_allow | length > 0
  ansible.builtin.lineinfile:
    path: "{{ nettime_keyfile }}"
    regexp: '^{{ nettime_keyid }} '
    line: "{{ chrony_key }}"
    state: present
    owner: root
    group: "{{ nettime_group }}"
    mode: 0640
  notify: Restart chronyd

- name: Set timezone
  community.general.timezone:
    name: "{{ timezone | default('UTC') }}"
  notify: Restart chronyd

- name: Is RTC time in local time zone
  ansible.builtin.shell: |
    set -o pipefail
    timedatectl|grep -c 'RTC in local TZ: yes'
  register: rtc_timezone
  changed_when: false
  failed_when: rtc_timezone.rc not in [0,1]

- name: Use RTC time in UTC not local time zone
  when: rtc_timezone.stdout|int == 1
  ansible.builtin.command: timedatectl set-local-rtc 0
  changed_when: true

- name: Configure chrony
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: "{{ nettime_config }}"
    owner: root
    group: root
    mode: 0644
  notify: Restart chronyd

- name: Manage daemon options
  when:
    - ansible_os_family == 'Debian'
    - ansible_distribution_release == '11'
  ansible.builtin.lineinfile:
    path: /etc/default/chrony
    regexp: '^DAEMON_OPTS='
    line: 'DAEMON_OPTS=""'
    state: present

- name: Set drift
  ansible.builtin.file:
    path: "{{ nettime_driftfile }}"
    owner: "{{ nettime_user }}"
    group: "{{ nettime_group }}"
    mode: 0640
    state: touch
  changed_when: false

- name: Enable chronyd
  ansible.builtin.systemd:
    name: "{{ nettime_service }}"
    enabled: true
  notify: Start chronyd

- name: Ensure goss directory exists
  ansible.builtin.file:
    path: /etc/goss.d
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Copy goss tests template
  ansible.builtin.template:
    src: test_nettime.yml.j2
    dest: /etc/goss.d/test_nettime.yml
    owner: root
    group: root
    mode: 0644
  tags:
    - goss
...
