---
galaxy_info:
  role_name: dhcp_setup
  namespace: bbaassssiiee
  author: Bas Meijer
  description: DHCP for Kickstart

  license: MIT

  min_ansible_version: "2.10.0"

  platforms:
    - name: EL
      versions:
        - "8"
  galaxy_tags:
    - system
    - kickstart
    - dhcp
    - bootp
dependencies: []
# List your role dependencies here, one per line.
# Be sure to remove the '[]' above,
# if you add dependencies to this list.
