---

  - name: Add an Ethernet connection with static IP configuration
    community.general.nmcli:
      autoconnect: true
      conn_name: eth1
      ifname: eth1
      type: ethernet
      ip4: 192.168.56.30/24
      gw4: 192.168.56.1
      state: present
