---
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_handlers.html
- name: Control service
  ansible.builtin.systemd:
    name: "{{ service }}"
    state: "{{ systemd_state }}"
    enabled: "{{ systemd_enabled }}"
    daemon_reload: true

- name: Restart firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: restarted
    daemon_reload: true
