---

- name: Setup GPG check for AlmaLinux
  block:
    - name: Copy GPG key
      ansible.builtin.copy:
        src: RPM-GPG-KEY-AlmaLinux-9
        dest: /etc/pki/rpm-gpg/
        mode: '0644'
    - name: Import GPG key
      ansible.builtin.rpm_key:
        key: /etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux-9

- name: List reposities
  ansible.builtin.command: yum repolist  # noqa: command-instead-of-module
  changed_when: false
  register: my_repolist

- name: Report enabled reposities
  ansible.builtin.debug:
    msg: "{{ my_repolist.stdout_lines }}"
    verbosity: 1

- name: Enable daily security updates
  when: automatic_updates | bool
  block:

    - name: Install dnf-automatic package
      ansible.builtin.dnf:
        name: dnf-automatic
        state: present

    - name: Create dnf-automatic configuration
      ansible.builtin.template:
        src: automatic.conf.j2
        dest: /etc/dnf/automatic.conf
        owner: root
        group: root
        mode: 0644

    - name: Install dnf-automatic-install timer
      ansible.builtin.systemd:
        name: dnf-automatic-install.timer
        daemon_reload: true
        state: started
        enabled: true
