---

- name: Re-configure for proxied use
  when:
    - proxy_host is defined
    - proxy_host | length > 3
  block:
    - name: Configure proxy for package management
      environment: "{{ proxy_env | default(omit) }}"
      ansible.builtin.template:
        src: dnf.conf.j2
        dest: /etc/dnf/dnf.conf
        owner: root
        group: root
        mode: '0600'
      no_log: false

    - name: Configure proxy for pip
      environment: "{{ proxy_env | default(omit) }}"
      ansible.builtin.template:
        src: pip.conf.j2
        dest: /etc/pip.conf
        owner: root
        group: root
        mode: '0600'
      no_log: false

    - name: Disable unneeded repo files
      ansible.builtin.lineinfile:
        path: "/etc/yum.repos.d/{{ item }}"
        regexp: '^enabled=*'
        line: 'enabled=0'
        mode: '0600'
      loop: "{{ yum_repofiles_unneeded }}"

    - name: Enable needed repo files
      ansible.builtin.lineinfile:
        path: "/etc/yum.repos.d/{{ item }}"
        regexp: '^enabled=*'
        line: 'enabled=1'
        mode: '0600'
      loop: "{{ yum_repofiles_unneeded }}"

    - name: Point repo files to repo_url
      when: repo_url is defined
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: "/etc/yum.repos.d/{{ item }}"
        owner: root
        group: root
        mode: '0600'
      loop: "{{ yum_repofiles_needed }}"
