---

timezone: UTC

# use nearby ntp servers if available
ntp_zone: .nl
ntp_pools: []
ntp_servers:
  - "0{{ ntp_zone if ntp_zone else '' }}.pool.ntp.org"
  - "1{{ ntp_zone if ntp_zone else '' }}.pool.ntp.org"
  - "2{{ ntp_zone if ntp_zone else '' }}.pool.ntp.org"
  - "3{{ ntp_zone if ntp_zone else '' }}.pool.ntp.org"

# sync time with LAN peers
ntp_peers: []

# allow access from these subnets
net_allow: []
# net_allow:
#   - '192.168.0.0/16'

# deny access from these subnets
net_deny: []

# unique integer for peer authentication
nettime_keyid: 123

# manage firewall of do it yourself for use as server
manage_firewall: true

start_nettime_service: true
...
