#!/usr/bin/env ansible-playbook
---

- name: Security Audit
  hosts: all:!localhost
  become: true
  gather_facts: true

  pre_tasks:

    - name: Install dependencies
      ansible.builtin.dnf:
        state: present
        name:
          - openscap-scanner
          - scap-security-guide

  post_tasks:

    - name: 'Run the audit and create a report.'
      ansible.builtin.command:
        oscap xccdf eval \
          --report /tmp/report.html
          --profile cis
          --fetch-remote-resources
          /usr/share/xml/scap/ssg/content/ssg-almalinux8-ds.xml
      changed_when: true
      no_log: false
      ignore_errors: true

    - name: 'Fetch the report.'
      ansible.builtin.fetch:
        flat: true
        src: /tmp/report.html
        dest: "~/Downloads/{{ inventory_hostname }}.html"
...
