#!/usr/bin/env ansible-playbook
# Usage: ./ks-server.yml -i inventory -e main_user=vagrant -e main_password=vagrant
---
- name: Create Kickstart server
  hosts: kickstart
  become: true
  gather_facts: true
  pre_tasks:
    - name: Check extra vars main_user and main_password
      ansible.builtin.assert:
        that:
          - desired_state == 'absent' or main_user is defined
          - desired_state == 'absent' or main_password is defined
  tags:
    - kickstart
  roles:
    - dual_homed
    - apache
    - tftp_setup
    - kickstart
    - dhcp_setup
