#!/usr/bin/env ansible-playbook -K
---

- name: Security Audit
  hosts: alma8
  become: true
  gather_facts: true

  pre_tasks:

    - name: Install packages
      ansible.builtin.package:
        state: present
        name:
          - openscap-scanner
          - scap-security-guide

  post_tasks:

    - name: Run CIS oscap scan and create ~/report.html
      ansible.builtin.command:
        oscap xccdf eval --profile cis \
          --report ~/report.html \
          --cpe /usr/share/xml/scap/ssg/content/ssg-almalinux8-cpe-dictionary.xml \
          /usr/share/xml/scap/ssg/content/ssg-almalinux8-xccdf.xml
      changed_when: true
      no_log: false
      register: scan_return
      failed_when: scan_return.stdout is not defined

    - name: Set permissions
      ansible.builtin.file:
        path: /tmp/report.html
        owner: "{{ ansible_ssh_user }}"
        mode: '0600'
