#!/usr/bin/env ansible-playbook
---

- name: Hardening
  hosts: all
  become: true
  gather_facts: true

  vars:
    crypto_policy: STRICT
    # We would rather use FUTURE, but
    # pypi.python.org still uses 2048-bit RSA.

  pre_tasks:
    - name: Set proxy environment
      ansible.builtin.set_fact:
        proxy_env:
          HTTPS_PROXY: "{{ https_proxy | default(omit) }}"
          PROXY_USER: "{{ proxy_user | default(omit) }}"
          PROXY_PASSWORD: "{{ proxy_password | default(omit) }}"
      no_log: true

  roles:
    - role: package_management
      repo_url: 'https://mirrors.xtom.nl/almalinux'
      tags: package_management
      # repo url is a mirror or internal repo/proxy for the RPM
      # xtom.nl is the only mirror usable with crypto_policy: FUTURE
    - role: rhel9cis
      tags: rhel9cis

...
