#!/usr/bin/env ansible-playbook
---

- name: Hardening
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: yum_config
      repo_url: 'https://almalinux.mirror.liteserver.nl/'
      # repo url is a mirror or internal repo/proxy for the RPMs
    - role: rhel8cis
      rhel8cis_rule_5_3_4: false
      rhel8cis_remote_log_server: loghost
    - role: openssh
      crypto_policy: FUTURE
    - base_line

...
