#!/usr/bin/env ansible-playbook
---

- name: Hardening
  hosts: all
  become: true
  gather_facts: true

  vars:
    rhel8cis_rule_5_3_4: false
    rhel8cis_remote_log_server: loghost
    crypto_policy: DEFAULT

  roles:
    - RHEL8-CIS
    - openssh
    - base_line

...
