#!/usr/bin/env ansible-playbook
---
- name: Create Kickstart server
  hosts: kickstart
  become: true
  gather_facts: true
  vars:
    # For the kickstarted client
    main_user: "{{ lookup('env', 'KS_USER') }}"
    main_password: "{{ lookup('env', 'KS_PASSWORD') }}"
  tags:
    - kickstart
  roles:
    - apache
    - tftp_setup
    - kickstart
    - dhcp_setup

- name: Deploy Proxy
  hosts: proxy
  become: true
  gather_facts: true
  tags:
    - proxy
  roles:
    - role: proxy

...
