#!/usr/bin/env ansible-playbook
# Usage: ./ks-server.yml -i inventory -e main_user=vagrant -e main_password=vagrant
---
- name: Harden machine
  hosts: all:!localhost
  become: true
  gather_facts: true
  tags:
    - harden
  roles:
    - base_line
    - openssh

- name: Create Web Server
  hosts: web
  become: true
  gather_facts: true
  roles:
    - apache

- name: Create Proxy Server
  hosts: proxy
  become: true
  gather_facts: true
  roles:
    - proxy

- name: Create Kickstart server
  hosts: kickstart
  become: true
  gather_facts: true
  vars:
    main_user: vagrant
    main_password: vagrant
  tags:
    - kickstart
  roles:
    - dual_homed
    - apache
    - tftp_setup
    - kickstart
    - dhcp_setup
