#!/usr/bin/env ansible-playbook
---
- name: Deploy Proxy
  hosts: proxy
  become: true
  gather_facts: true
  tags:
    - proxy
  roles:
    - role: proxy

- name: Create Kickstart server
  hosts: web
  become: true
  gather_facts: true
  tags:
    - web
  roles:
    - apache
    - tftp_setup
    - kickstart
    - dhcp_setup

...
