#!/usr/bin/env ansible-playbook
# Usage: ./ks-server.yml -i inventory -e main_user=vagrant -e main_password=vagrant
---

- name: Create Proxy Server
  hosts: proxy_servers
  become: true
  gather_facts: true
  tags:
    - proxy
  roles:
    - proxy

- name: Create Kickstart server
  hosts: kickstart_servers
  become: true
  gather_facts: true
  vars:
    main_user: vagrant
    main_password: vagrant
  tags:
    - kickstart
  roles:
    - dual_homed
    - apache
    - tftp_setup
    - kickstart
    - dhcp_setup
