---
- name: Converge
  hosts: all
  vars:
    this_role: "{{ lookup('env','MOLECULE_PROJECT_DIRECTORY') | basename }}"
    manage_firewall: false
    # yamllint disable-line rule:line-length
    chrony_key: '1234 SHA256 HEX:DD4E59D2CAE16FFCEBF23D67201814A2FA63251E1B23A1AF3A99203121807C6C'

  tasks:
    - name: "Include {{ this_role }}"
      ansible.builtin.include_role:
        name: "{{ this_role }}"
...
